src/django18/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django18 import views

urlpatterns = [
    url(r'^newsletter/', include('newsletter.urls', namespace='newsletter')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'about/', views.index, name='about'),
    url(r'^accounts/', include('registration.backends.default.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/newslatter/urls.py
from django.conf.urls import url
from newslatter import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
]

src/newsletter/urls.py
from django.conf.urls import url
from newsletter import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
]

src/newsletter/models.py
from django.db import models


class SignUp(models.Model):
    email = models.EmailField()
    full_name = models.CharField(max_length=120, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

src/newslatter/forms.py
import re
from django import forms
from newslatter.models import SignUp


class ContactForm(forms.Form):
    email = forms.EmailField()
    full_name = forms.CharField(required=False)
    message = forms.CharField()

    def clean_email(self):
        email = self.data.get('email')
        if not re.match(r'[a-zA-Z][\w]{4,32}@[a-z\d]{3,}([.]+[a-z0-9]{2,})+', email):
            raise forms.ValidationError('Email format error.')
        return email


class SignUpForm(forms.ModelForm):

    class Meta:
        model = SignUp
        fields = ['email', 'full_name']

    def clean_email(self):
        email = self.data.get('email')
        if not re.match(r'[a-zA-Z][\w]{4,32}@[a-z\d]{3,}([.]+[a-z0-9]{2,})+', email):
            raise forms.ValidationError('Email format error.')
        instance = SignUp.objects.filter(email=email)
        if instance.exists():
            raise forms.ValidationError('Email has already benn used.')
        return email

src/newsletter/forms.py
import re
from django import forms
from newsletter.models import SignUp


class ContactForm(forms.Form):
    email = forms.EmailField()
    full_name = forms.CharField(required=False)
    message = forms.CharField()

    def clean_email(self):
        email = self.data.get('email')
        if not re.match(r'[a-zA-Z][\w]{4,32}@[a-z\d]{3,}([.]+[a-z0-9]{2,})+', email):
            raise forms.ValidationError('Email format error.')
        return email


class SignUpForm(forms.ModelForm):

    class Meta:
        model = SignUp
        fields = ['email', 'full_name']

    def clean_email(self):
        email = self.data.get('email')
        if not re.match(r'[a-zA-Z][\w]{4,32}@[a-z\d]{3,}([.]+[a-z0-9]{2,})+', email):
            raise forms.ValidationError('Email format error.')
        instance = SignUp.objects.filter(email=email)
        if instance.exists():
            raise forms.ValidationError('Email has already benn used.')
        return email

src/django18/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'about.html', {})

src/newslatter/views.py
from django.shortcuts import render
from newslatter.forms import SignUpForm, ContactForm


def index(request):
    form = SignUpForm(request.POST or None)
    if form.is_valid():
        form.save()
    return render(request, 'index.html', {'form': form})


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        for k, v in form.cleaned_data.items():
            print(k, v)
    return render(request, 'forms.html', {'form': form})

src/newsletter/views.py
from django.shortcuts import render
from newsletter.forms import SignUpForm, ContactForm


def index(request):
    form = SignUpForm(request.POST or None)
    if form.is_valid():
        form.save()
    return render(request, 'index.html', {'form': form, 'title': 'Welcome'})


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        for k, v in form.cleaned_data.items():
            print(k, v)
    return render(request, 'forms.html', {'form': form, 'title': 'Contact Us ...'})

src/templates/base.html
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/navbar-static-top/">

    <title>{% block head_title %}MVP Landing{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <style>
      {% block style %}
      {% endblock %}
    </style>
  </head>

  <body>
    {% include 'nav-bar.html' %}
    {% block jumbotron %}
    {% endblock %}

    <div class="container">
    {% block content %}
    {% endblock %}
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

src/templates/forms.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact</title>
</head>
<body>
    {% block content %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            {% if title %}
            <h1 class="lead">{{ title }}</h1>
            {% endif %}
            <form method="post" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="submit">
            </form>
        </div>
    </div>
    {% endblock %}
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Welcome | {{ block.super }}{%  endblock %}</title>
	<style>
		{% block style %}
		.jumbotron {
			background-color: #0C4B33;
			color: white;
		}

		.navbar-static-top {
			margin-bottom: 0 !important;
		}
		{% endblock %}
	</style>
</head>
<body>
	{% block jumbotron %}
	<div class="jumbotron">
		<div class="container">
			<div class="row">
				<div class='col-sm-6'>
					<h1>Try Django 1.8</h1>
					<p>The MVP Landing project is designed to get your project started. The goal is to help you launch as soon as possible with the least amount of investment using time or money. Join Us today.</p>
					<p><a class="btn btn-lg btn-primary" href="" role="button">Join Us &raquo;</a></p>
				</div>
				<div class='col-sm-6'>
					<iframe width="560" height="315" src="https://www.youtube.com/embed/e6nOQRvOP7w" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
				</div>
			</div>
		</div>
	</div>
	{% endblock %}

	{% block content %}
	<div class="row">
		<!-- use xs 就會以此當最小基準 -->
		<!--<div class="col-sm-6 col-md-3">-->
		<div class="col-xs-3 pull-right">
			<p class="lead text-align-center">{{ title }}</p>
			<form method="post" action="">
		        {% csrf_token %}
		        {{ form|crispy }}
		        <input class="btn btn-primary" type="submit" value="submit">
	        </form>
		</div>

		<div class="col-xs-3">
			<p class="lead text-align-center">Built with Django &amp; Bootstrap</p>
		</div>

		<div class="col-xs-3">
			<p class="lead text-align-center">Created for Starters of all kinds.</p>
		</div>

		<div class="col-xs-3">
			<p class="lead text-align-center">Always Open Source</p>
		</div>
	</div>
	{% endblock %}
</body>
</html>

src/templates/nav-bar.html
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'newsletter:index' %}">MVP Landing</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'newsletter:contact' %}">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'auth_logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'auth_login' %}">Login</a></li>
        {% endif %}
        <li><a href="{% url 'registration_register' %}">Register</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>